### ISSUE TITLE
vsphere creds duplicate

### ISSUE THREAD

**Issue by a-dawg** [albertogd/gitops-for-organizations#24]
hello,
I am wondering if there is any way to utilize the vsphere-creds secret instead of also setting it into install-config.yml? RHACM does not seem to support that. vsphere-creds does not looks to be used while deploying the cluster. Do you think a feature request should be raised to redhat?

**Comment by albertogd** [comment]
hello @a-dawg,

The credentials are in 2 places, although the purpose of each place is different:

- The credentials in `install-config` are used/consumed by openshift-installer. 

- The credentials in `vsphere-creds` secret (referenced in the `ClusterDeployment`) are used by Hive/ACM to create cloud clients for:
  - hibernate/resume (to stop/start the instances, only supported in Azure/AWS/GCP)
  - syncsets
  - machinepools
  - version labels
  - reachability probe

When you create a cluster in ACM (GUI), you just need to create the credentials once, and they are added in `install-config`. This is an "extra" of the ACM GUI. But from Hive perspective, `vsphere-creds` secret and credentials in `install-config` are used by different components.

When you create a cluster using gitops, you just need to have the credentials configured (once) in a Vault. You should add the reference to the same Vault key credentials in the `install-config`  secret and in the `vsphere-creds` objec.

For example, using [External Secret Operator](https://cloud.redhat.com/blog/how-to-feed-external-secrets-for-kubernetes-applications-with-the-external-secret-operator-and-gitlab-on-red-hat-openshift), you can create both Secrets with the vSphere user/password from the values in your Vault.
